// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// authMenuDao is the data access object for the table auth_menu.
// You can define custom methods on it to extend its functionality as needed.
type authMenuDao struct {
	*internal.AuthMenuDao
}

var (
	// AuthMenu is a globally accessible object for table auth_menu operations.
	AuthMenu = authMenuDao{internal.NewAuthMenuDao()}
)

// Add your custom methods and functionality below.
