// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// authApiDao is the data access object for the table auth_api.
// You can define custom methods on it to extend its functionality as needed.
type authApiDao struct {
	*internal.AuthApiDao
}

var (
	// AuthApi is a globally accessible object for table auth_api operations.
	AuthApi = authApiDao{internal.NewAuthApiDao()}
)

// Add your custom methods and functionality below.
