// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// authRoleApiDao is the data access object for the table auth_role_api.
// You can define custom methods on it to extend its functionality as needed.
type authRoleApiDao struct {
	*internal.AuthRoleApiDao
}

var (
	// AuthRoleApi is a globally accessible object for table auth_role_api operations.
	AuthRoleApi = authRoleApiDao{internal.NewAuthRoleApiDao()}
)

// Add your custom methods and functionality below.
