// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// authRoleMenuDao is the data access object for the table auth_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type authRoleMenuDao struct {
	*internal.AuthRoleMenuDao
}

var (
	// AuthRoleMenu is a globally accessible object for table auth_role_menu operations.
	AuthRoleMenu = authRoleMenuDao{internal.NewAuthRoleMenuDao()}
)

// Add your custom methods and functionality below.
