// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// sysPlatformDao is the data access object for the table sys_platform.
// You can define custom methods on it to extend its functionality as needed.
type sysPlatformDao struct {
	*internal.SysPlatformDao
}

var (
	// SysPlatform is a globally accessible object for table sys_platform operations.
	SysPlatform = sysPlatformDao{internal.NewSysPlatformDao()}
)

// Add your custom methods and functionality below.
