// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"charon-janus/internal/dao/internal"
)

// sysAuthRolesDao is the data access object for the table sys_auth_roles.
// You can define custom methods on it to extend its functionality as needed.
type sysAuthRolesDao struct {
	*internal.SysAuthRolesDao
}

var (
	// SysAuthRoles is a globally accessible object for table sys_auth_roles operations.
	SysAuthRoles = sysAuthRolesDao{internal.NewSysAuthRolesDao()}
)

// Add your custom methods and functionality below.
